[package]
name = "mirror-cli"
version = "0.6.1"
authors = ["dev <dev@qiyutech.tech>"]
edition = "2018"
description = "镜像配置&管理工具"
license-file = "LICENSE"
homepage = "https://github.com/QiYuTechDev/mirror"

[[bin]]
name = "mirror"
path = "src/main.rs"

[dependencies]
structopt = "0.3"
which = "5.0"
